// Code generated by 'yaegi extract mvdan.cc/sh/shell'. DO NOT EDIT.

package lib

import (
	"mvdan.cc/sh/shell"
	"reflect"
)

func init() {
	Symbols["mvdan.cc/sh/shell/shell"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Expand": reflect.ValueOf(shell.Expand),
	}
}
