#!/bin/sh

set -eu

print_package_reference() (
	dir="$PWD/reference/$1"
	mkdir -p "$dir"
	cd "$dir"
	echo constants variables functions types | xargs -n1 touch 

	kind=
	pkg_h="$(go doc -all -short "$1" | sed -E 's/^ +(.*)$/\/\/ \1/g' | grep -Ev '^(|//.*)$')"

	while :; do
		pkg_h_tail="$(echo "$pkg_h" | sed -En '/^([A-Z]+)$/,$p')"
		
		case "$kind" in
			constants|variables|functions|types)
				echo "$pkg_h" | head -n -"$(echo "$pkg_h_tail" | wc -l)" > $kind
			;;
			"")
				:
			;;
			*)
				echo "unknown section '$kind'" >&2
			;;
		esac

		if test -z "$pkg_h_tail"; then
			break
		fi

		kind="$(echo "$pkg_h_tail" | head -n 1 | tr [A-Z] [a-z])"
		pkg_h="$(echo "$pkg_h_tail" | tail -n +2)"
	done
)

cd "$(dirname $0)/.."

packages="$(./yaegi -packages -packages | sort | uniq -u)"
index=0

for package in $packages; do
	echo "$((++index)): $package" >&2
	print_package_reference "$package"
done
